### ISSUE TITLE
Controller R490 errors 

### ISSUE THREAD

**Issue by Rakon23** [CompitHomeAssistant/HomeAssistant#5]
r490 controller. No setting of manual operation temperature 1 and heating curve. No control manual operation - automatic - stop. No control wrong return temperature indication. There are a few other errors, but these are the most recommended for correction, because the lack of control from the HA level makes this integration useless

**Comment by Rakon23** [comment]
Rejestrator: homeassistant.util.loop
Źródło: util/loop.py:136
Pierwsze zdarzenie: 04:30:18 (1 zdarzenia)
Ostatnio zalogowany: 04:30:18

Detected blocking call to open with args ('/config/custom_components/compit/definitions/devices_pl.json', 'r') inside the event loop by custom integration 'compit' at custom_components/compit/__init__.py, line 60: with open(file_path, 'r', encoding='utf-8') as file: (offender: /config/custom_components/compit/__init__.py, line 60: with open(file_path, 'r', encoding='utf-8') as file:), please create a bug report at https://github.com/CompitHomeAssistant/HomeAssistant/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/compit/__init__.py", line 21, in async_setup_entry device_definitions = await get_device_definitions(hass, hass.config.language) File "/config/custom_components/compit/__init__.py", line 60, in get_device_definitions with open(file_path, 'r', encoding='utf-8') as file:

**Comment by Rakon23** [comment]
> r490 controller. No setting of manual operation temperature 1 and heating curve. No control manual operation - automatic - stop. No control wrong return temperature indication. There are a few other errors, but these are the most recommended for correction, because the lack of control from the HA level makes this integration useless

After modifying the integration, I was able to expose the additional entities I needed — specifically the operating mode selectors.
However, after the most recent update, the integration again only exposes 29 entities, and the operating mode entities are missing.
Based on previous functionality, there should be approximately 49 entities available, so a significant number are not being created.

**Comment by Przemko92** [comment]
Please check on new 2.0.0 version.
